import { expect, test } from '@playwright/test'

test('administrator can inspect the fleet and publish a tested module', async ({ page }) => {
  await page.goto('/admin/login')
  await expect(page.getByRole('heading', { name: 'Вход в консоль' })).toBeVisible()
  await page.getByLabel('Имя пользователя').fill('console-e2e')
  await page.getByLabel('Пароль').fill('console-e2e-password')
  const loginResponse = page.waitForResponse(response => response.url().endsWith('/api/admin/session'))
  const sessionResponse = page.waitForResponse(response => response.url().includes('/api/admin/console/session'))
  await page.getByRole('button', { name: 'Войти' }).click()
  expect((await loginResponse).status()).toBe(201)
  expect((await sessionResponse).status()).toBe(200)
  await expect(page.getByRole('heading', { name: 'Состояние парка' })).toBeVisible()

  await page.getByRole('navigation', { name: 'Основная навигация' }).getByRole('link', { name: 'Устройства' }).click()
  await expect(page.getByRole('heading', { name: 'Устройства', exact: true }).first()).toBeVisible()
  await expect(page.getByText('Тестовый компьютер')).toBeVisible()
  await page.getByRole('link', { name: 'Открыть' }).first().click()
  await expect(page.getByRole('heading', { name: 'Тестовый компьютер' })).toBeVisible()
  await page.getByRole('button', { name: 'Контекст' }).click()
  await expect(page.getByRole('button', { name: 'Обновить данные' })).toBeVisible()
  await page.getByRole('button', { name: 'Обновить данные' }).click()
  await expect(page.getByText(/^Сбор:/)).toBeVisible()
  await page.getByRole('button', { name: 'Изменения' }).click()
  await expect(page.getByRole('heading', { name: 'Изменения Context' })).toBeVisible()

  await page.getByRole('navigation', { name: 'Основная навигация' }).getByRole('link', { name: 'Установка и регистрация' }).click()
  await expect(page.getByRole('heading', { name: 'Установка и регистрация' })).toBeVisible()
  await page.getByRole('button', { name: 'Запросы' }).click()
  await expect(page.getByText('Тестовая заявка')).toBeVisible()

  await page.getByRole('navigation', { name: 'Основная навигация' }).getByRole('link', { name: 'Релизы и обновления' }).click()
  await expect(page.getByRole('heading', { name: 'Релизы и обновления' })).toBeVisible()
  await page.getByRole('navigation', { name: 'Разделы обновлений' }).getByRole('button', { name: 'Развёртывания' }).click()
  await expect(page.getByText('3.2.63 · Канареечное')).toBeVisible()
  await page.getByRole('button', { name: 'Открыть' }).click()
  await expect(page.getByRole('dialog', { name: 'Развёртывание' }).getByRole('heading', { name: 'Устройства · 1' })).toBeVisible()
  await page.getByRole('dialog', { name: 'Развёртывание' }).getByRole('button', { name: 'Закрыть' }).click()
  await page.getByRole('button', { name: 'Создать канареечное обновление' }).click()
  await expect(page.getByRole('heading', { name: 'Канареечное обновление' })).toBeVisible()
  await page.getByRole('dialog').getByRole('button', { name: 'Закрыть' }).click()

  await page.getByRole('navigation', { name: 'Основная навигация' }).getByRole('link', { name: 'Модули' }).click()
  await expect(page.getByText('РЕДАКТОР МОДУЛЕЙ')).toBeVisible()
  const draft = page.locator('form').last()
  await draft.getByLabel('Название').fill('Проверка сети')
  await draft.getByLabel('Module key').fill('network.basic.check')
  await draft.getByRole('button', { name: 'Добавить вход' }).click()
  await draft.getByLabel('Имя', { exact: true }).fill('target')
  await draft.getByRole('button', { name: 'Добавить шаг' }).click()
  await draft.getByRole('combobox', { name: 'Вход', exact: true }).first().selectOption('target')
  await draft.getByRole('combobox', { name: 'family' }).selectOption('literal')
  await draft.getByRole('button', { name: 'Создать черновик' }).click()
  await expect(page.getByRole('status')).toContainText('Черновик создан')
  await page.getByRole('button', { name: 'Проверить модуль' }).click()
  await expect(page.getByRole('status')).toContainText('Проверка: выполнено')
  await expect(page.getByRole('button', { name: 'Принять испытания' })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Опубликовать' })).toBeDisabled()
  await page.getByLabel('Совместимое устройство').selectOption({ label: 'Лабораторный Agent' })
  await page.getByLabel('target (строка)').fill('api.example.test')
  const labResponse = page.waitForResponse(response => response.url().includes('/lab-operations/') && response.request().method() === 'POST')
  await page.getByRole('button', { name: 'Запустить испытание' }).click()
  const lab = await labResponse
  expect(lab.status()).toBe(201)
  const operationId = (await lab.json()).data.operation_id as string
  const simulatedAgent = await page.request.post(`/__test__/complete-lab/${operationId}`)
  expect(simulatedAgent.status()).toBe(200)
  await expect(page.getByRole('button', { name: 'Сохранить подтверждение испытания' })).toBeVisible()
  await page.getByRole('button', { name: 'Сохранить подтверждение испытания' }).click()
  await expect(page.getByRole('status')).toContainText('Результат испытания сохранён')
  await expect(page.getByRole('button', { name: 'Принять испытания' })).toBeEnabled()
  await page.getByRole('button', { name: 'Принять испытания' }).click()
  await expect(page.getByRole('status')).toContainText('Принятие испытаний: выполнено')
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: 'Опубликовать' }).click()
  await expect(page.getByRole('status')).toContainText('Публикация: выполнено')

  await page.getByRole('navigation', { name: 'Основная навигация' }).getByRole('link', { name: 'Аудит' }).click()
  await expect(page.getByRole('heading', { name: 'Аудит' })).toBeVisible()
  await expect(page.getByText('Вход администратора')).toBeVisible()
  await page.getByLabel('Действие').fill('admin_session.created')
  await expect(page.getByText('Вход администратора')).toBeVisible()
})
